-- begin TESTTASK2_DVD
alter table TESTTASK2_DVD add constraint FK_TESTTASK2_DVD_ON_OWNER foreign key (OWNER_ID) references TESTTASK2_DVD_OWNER(ID)^
create index IDX_TESTTASK2_DVD_ON_OWNER on TESTTASK2_DVD (OWNER_ID)^
-- end TESTTASK2_DVD
-- begin TESTTASK2_DVD_OWNER
alter table TESTTASK2_DVD_OWNER add constraint FK_TESTTASK2_DVD_OWNER_ON_SYSTEM_USER foreign key (SYSTEM_USER_ID) references SEC_USER(ID)^
create index IDX_TESTTASK2_DVD_OWNER_ON_SYSTEM_USER on TESTTASK2_DVD_OWNER (SYSTEM_USER_ID)^
-- end TESTTASK2_DVD_OWNER
