alter table TESTTASK2_DVD_OWNER add constraint FK_TESTTASK2_DVD_OWNER_ON_SYSTEM_USER foreign key (SYSTEM_USER_ID) references SEC_USER(ID);
create index IDX_TESTTASK2_DVD_OWNER_ON_SYSTEM_USER on TESTTASK2_DVD_OWNER (SYSTEM_USER_ID);
