-- begin TESTTASK2_DVD
alter table TESTTASK2_DVD add constraint FK_TESTTASK2_DVD_ON_OWNER foreign key (OWNER_ID) references TESTTASK2_DVD_OWNER(ID)^
create index IDX_TESTTASK2_DVD_ON_OWNER on TESTTASK2_DVD (OWNER_ID)^
-- end TESTTASK2_DVD
-- begin TESTTASK2_DVD_OWNER
alter table TESTTASK2_DVD_OWNER add constraint FK_TESTTASK2_DVD_OWNER_ON_SYSTEM_USER foreign key (SYSTEM_USER_ID) references SEC_USER(ID)^
create index IDX_TESTTASK2_DVD_OWNER_ON_SYSTEM_USER on TESTTASK2_DVD_OWNER (SYSTEM_USER_ID)^
-- end TESTTASK2_DVD_OWNER
-- begin TESTTASK2_ITEM_TAKEN
alter table TESTTASK2_ITEM_TAKEN add constraint FK_TESTTASK2_ITEM_TAKEN_ON_CURRENT_OWNER foreign key (CURRENT_OWNER_ID) references TESTTASK2_DVD_OWNER(ID)^
alter table TESTTASK2_ITEM_TAKEN add constraint FK_TESTTASK2_ITEM_TAKEN_ON_TAKEN_DVD foreign key (TAKEN_DVD_ID) references TESTTASK2_DVD(ID)^
create index IDX_TESTTASK2_ITEM_TAKEN_ON_CURRENT_OWNER on TESTTASK2_ITEM_TAKEN (CURRENT_OWNER_ID)^
create index IDX_TESTTASK2_ITEM_TAKEN_ON_TAKEN_DVD on TESTTASK2_ITEM_TAKEN (TAKEN_DVD_ID)^
-- end TESTTASK2_ITEM_TAKEN
